# Generated by Django 4.2.3 on 2023-07-04 00:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import socials.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('file', models.FileField(upload_to=socials.models.social_directory_path)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('shares', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('header', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('autogenerated', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
