import uuid as uuid

from allauth.socialaccount.models import SocialAccount
from django.db import models
from django_extensions.db.models import TimeStampedModel


def social_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}/{2}'.format(instance.account.user.username, instance.account.platform, filename)


class SocialPost(TimeStampedModel):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4)
    account = models.ForeignKey(SocialAccount, on_delete=models.CASCADE, blank=True, null=True)
    date_published = models.DateTimeField(blank=True, null=True)
    content = models.TextField()
    # The file field can be used to store video or images
    file = models.FileField(upload_to=social_directory_path)
    likes = models.IntegerField(blank=True, null=True)
    comments = models.IntegerField(blank=True, null=True)
    shares = models.IntegerField(blank=True, null=True)
    published = models.BooleanField(default=False)
    header = models.JSONField(default=dict)
    data = models.JSONField(default=dict)
    response = models.JSONField(default=dict)
    autogenerated = models.BooleanField(default=False)

